### ISSUE TITLE
[Bruteforece Testing]송금 시 비밀번호를 3회 이상 틀렸을 때 예외처리를 확인 한다.

### ISSUE THREAD

**Issue by 3ssarah** [ansrl0107/softwareModeling#12]
송금 시 비밀번호를 3회 이상 틀렸을 때 에러를 발생시키지 않고, 비밀번호가
틀렸을 때의 에러와 동일한 에러가 발생한다.

**Comment by gds04070** [comment]
지난 문서와 코드의 불일치로 인해 새로 수정한 문서에서는 비밀번호를 3회 이상 틀렸을때 예외처리하는 것이 아니라 에러 메시지만 띄우고 계속 입력받을 수 있도록 수정하였습니다.
