### ISSUE TITLE
[Bruteforce Testing]입금 내역이 많을 경우 1초 이내에 처리 되는지 확인

### ISSUE THREAD

**Issue by 3ssarah** [ansrl0107/softwareModeling#13]
입금메뉴 선택 후, log.txt 파일이 50MB가 넘은 계좌번호를 입력하고 확인 버튼을
누르면 약 5초 후 메뉴가 표시된다.

**Comment by gds04070** [comment]
반응 속도를 1초 내로 줄여보려 했지만 코드 구조, 설계를 수정해야 하는 것으로 결론이 났습니다.
지금 당장 1초 내로 반응 속도를 줄이기는 어렵다고 생각합니다.
