### ISSUE TITLE
[11]1000.1100.1200.2000.3000.3100.3200.4000.4100.4200.5000.5100.

### ISSUE THREAD

**Issue by 3ssarah** [ansrl0107/softwareModeling#28]
Account             :  계좌번호 존재
   Password            :  일치
   ATM Balance         :  충분
   Account Balance     :  충분
   Transaction Log     :  거래기록 파일이 있는 경우
   Criminal Log        :  범죄기록 파일이 있는 경우
   Transaction History :  거래내역 있는 경우
   Criminal History    :  범죄기록 있는 경우
   Deposit             :  타행입금
   Withdraw            :  타행출금
   Transfer            :  타행송금
   Transaction Result  :  입금
   Statement           :  명세표 출력 => **명세표 출력이 없음**
   Account Number      :  숫자로만 입력
   Password Number     :  입력
   Transaction Amount  :  숫자로만 입력

**Comment by 3ssarah** [comment]
1000.1100.1200.2100.3000.3100.3200.4000.4100.4200.5000.5100. (12)
1000.1100.1200.2200.3000.3100.3200.4000.4100.4200.5000.5100.(13)
1000.1100.1200.2001.3000.3100.3200.4000.4100.4200.5000.5100.(14)
1000.1100.1200.2101.3000.3100.3200.4000.4100.4200.5000.5100.(15)
1000.1100.1200.2201.3000.3100.3200.4000.4100.4200.5000.5100.(16)
1000.1100.1200.2000.3000.3101.3200.4000.4100.4200.5000.5100.(17)
1000.1100.1200.2100.3000.3101.3200.4000.4100.4200.5000.5100.(18)

**Comment by ansrl0107** [comment]
현실에서 출력이 불가능 하여 거래가 끝난후 모니터에 거래 내역을 보여주는 것으로 대체함
